# Generated by Django 5.2.17 on 2026-10-04 13:53

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('identity', '0002_organizations_teams_and_email_login'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'inventory_warehouse',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='suppliers.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_receipt',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('available', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('on_hand'), '-', models.F('reserved')), output_field=models.IntegerField())),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_item',
                'ordering': ('warehouse__code',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('RESERVATION', 'RESERVATION'), ('RELEASE', 'RELEASE'), ('SALE', 'SALE'), ('ADJUSTMENT', 'ADJUSTMENT'), ('RETURN', 'RETURN'), ('TRANSFER', 'TRANSFER')], max_length=20)),
                ('on_hand_delta', models.IntegerField()),
                ('reserved_delta', models.IntegerField()),
                ('on_hand_after', models.IntegerField()),
                ('reserved_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=30)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='inventory_movement_recent_idx'), models.Index(fields=['stock_item', '-created_at'], name='inventory_movement_item_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_movement_ref_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('on_hand_delta', 0), ('reserved_delta', 0), _negated=True), name='inventory_movement_nonzero_check'), models.CheckConstraint(condition=models.Q(('type__in', ['PURCHASE', 'RESERVATION', 'RELEASE', 'SALE', 'ADJUSTMENT', 'RETURN', 'TRANSFER'])), name='inventory_movement_type_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='inventory_warehouse_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9-]{2,20}$')), name='inventory_warehouse_code_format_check'),
        ),
        migrations.AddConstraint(
            model_name='stockreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('organization', 'supplier', 'document_number'), name='inventory_receipt_org_supplier_document_uniq', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['organization', 'warehouse'], name='inventory_stock_org_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['organization', 'available'], name='inventory_stock_available_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='inventory_stock_item_product_warehouse_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='inventory_stock_item_on_hand_non_negative_check'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='inventory_stock_item_reserved_non_negative_check'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='inventory_stock_item_reserved_lte_on_hand_check'),
        ),
    ]
