# Generated by Django 5.2.17 on 2026-10-06 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
        ('inventory', '0002_stock_movement_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('order_line_id', models.UUIDField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CONFIRMED', 'CONFIRMED'), ('CONSUMED', 'CONSUMED'), ('RELEASED', 'RELEASED'), ('EXPIRED', 'EXPIRED')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_stock_reservation',
                'indexes': [models.Index(fields=['order_id'], name='inventory_resv_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_reservation_quantity_check'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'CONFIRMED', 'CONSUMED', 'RELEASED', 'EXPIRED'])), name='inventory_reservation_status_check'), models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'CONFIRMED'])), fields=('order_line_id', 'stock_item'), name='inventory_reservation_one_holding_per_line_uniq')],
            },
        ),
    ]
