# Generated by Django 5.2.17 on 2026-10-07 15:14

import apps.notifications.domain.kinds
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ORDER_CONFIRMED', 'ORDER_CONFIRMED'), ('ORDER_PAID', 'ORDER_PAID'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('ORDER_DELIVERED', 'ORDER_DELIVERED'), ('ORDER_CANCELLED', 'ORDER_CANCELLED'), ('ORDER_REFUNDED', 'ORDER_REFUNDED'), ('STOCK_LOW', 'STOCK_LOW'), ('USER_INVITATION', 'USER_INVITATION'), ('PASSWORD_RESET', 'PASSWORD_RESET')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], max_length=10)),
                ('source_event_id', models.UUIDField()),
                ('reference_id', models.UUIDField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'reference_id'], name='notifications_reference_idx'), models.Index(condition=models.Q(('status', apps.notifications.domain.kinds.NotificationStatus['PENDING'])), fields=['updated_at'], name='notifications_pending_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_event_id', 'recipient_email'), name='notifications_one_per_event_recipient_uniq'), models.CheckConstraint(condition=models.Q(('kind__in', ['ORDER_CANCELLED', 'ORDER_CONFIRMED', 'ORDER_DELIVERED', 'ORDER_PAID', 'ORDER_REFUNDED', 'ORDER_SHIPPED', 'PASSWORD_RESET', 'STOCK_LOW', 'USER_INVITATION'])), name='notifications_kind_check'), models.CheckConstraint(condition=models.Q(('status__in', ['FAILED', 'PENDING', 'SENT', 'SKIPPED'])), name='notifications_status_check'), models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', False), ('status', apps.notifications.domain.kinds.NotificationStatus['SENT'])), models.Q(models.Q(('status', apps.notifications.domain.kinds.NotificationStatus['SENT']), _negated=True), ('sent_at__isnull', True)), _connector='OR'), name='notifications_sent_at_check'), models.CheckConstraint(condition=models.Q(('status', apps.notifications.domain.kinds.NotificationStatus['SKIPPED']), models.Q(('recipient_email', ''), _negated=True), _connector='OR'), name='notifications_recipient_check')],
            },
        ),
    ]
