# Generated by Django 5.2.17 on 2026-10-05 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('identity', '0002_organizations_teams_and_email_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='customers.customersegment')),
            ],
            options={
                'db_table': 'pricing_price_list',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'db_table': 'pricing_price_list_item',
            },
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='pricing_price_list_org_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('segment__isnull', True)), fields=('organization',), name='pricing_price_list_one_default_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('segment__isnull', False)), fields=('organization', 'segment'), name='pricing_price_list_one_per_segment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'BRL')), name='pricing_price_list_currency_check'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['product', 'price_list'], name='pricing_item_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.UniqueConstraint(fields=('price_list', 'product'), name='pricing_item_list_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='pricing_item_unit_price_non_negative_check'),
        ),
    ]
