# Generated by Django 5.2.17 on 2026-10-06 14:41

import apps.orders.domain.status
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('identity', '0002_organizations_teams_and_email_login'),
        ('inventory', '0003_stock_reservation'),
        ('orders', '0002_status_history_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', apps.orders.domain.status.OrderStatus['AWAITING_PAYMENT'])), fields=['payment_due_at'], name='orders_awaiting_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', apps.orders.domain.status.OrderStatus['AWAITING_PAYMENT']), _negated=True), ('payment_due_at__isnull', False), _connector='OR'), name='orders_order_payment_due_check'),
        ),
    ]
