# Generated by Django 5.2.17 on 2026-10-07 16:30

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # Índice em tabela com volume: CONCURRENTLY não bloqueia escritas durante o deploy (exige
    # migration fora de transação).
    atomic = False

    dependencies = [
        ('customers', '0001_initial'),
        ('identity', '0002_organizations_teams_and_email_login'),
        ('inventory', '0003_stock_reservation'),
        ('orders', '0003_awaiting_payment_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='order',
            index=models.Index(condition=models.Q(('submitted_at__isnull', False)), fields=['organization', '-submitted_at'], name='orders_org_submitted_idx'),
        ),
    ]
