# Generated by Django 5.2.17 on 2026-10-08 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ORDER_CANCELLED', 'ORDER_CANCELLED'), ('ORDER_CREATED', 'ORDER_CREATED'), ('ORDER_STATUS_CHANGED', 'ORDER_STATUS_CHANGED'), ('PAYMENT_APPROVED', 'PAYMENT_APPROVED'), ('PAYMENT_DECLINED', 'PAYMENT_DECLINED'), ('PAYMENT_FAILED', 'PAYMENT_FAILED'), ('PAYMENT_RECORDED', 'PAYMENT_RECORDED'), ('PAYMENT_REFUNDED', 'PAYMENT_REFUNDED'), ('PAYMENT_STARTED', 'PAYMENT_STARTED'), ('REFUND_COMPLETED', 'REFUND_COMPLETED'), ('REFUND_FAILED', 'REFUND_FAILED'), ('REFUND_REQUESTED', 'REFUND_REQUESTED'), ('REFUND_RETRIED', 'REFUND_RETRIED'), ('REORDER_POINT_CHANGED', 'REORDER_POINT_CHANGED'), ('STOCK_ADJUSTED', 'STOCK_ADJUSTED'), ('STOCK_RECEIVED', 'STOCK_RECEIVED'), ('STOCK_TRANSFERRED', 'STOCK_TRANSFERRED')], max_length=40)),
                ('entity_type', models.CharField(choices=[('ORDER', 'ORDER'), ('PAYMENT', 'PAYMENT'), ('REFUND', 'REFUND'), ('STOCK_ITEM', 'STOCK_ITEM')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('entity_label', models.CharField(max_length=120)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('source_event_id', models.UUIDField(unique=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='audit_org_occurred_idx'), models.Index(fields=['organization', 'entity_type', 'entity_id'], name='audit_org_entity_idx'), models.Index(fields=['organization', 'order_id'], name='audit_org_order_idx'), models.Index(fields=['occurred_at'], name='audit_retention_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['ORDER_CANCELLED', 'ORDER_CREATED', 'ORDER_STATUS_CHANGED', 'PAYMENT_APPROVED', 'PAYMENT_DECLINED', 'PAYMENT_FAILED', 'PAYMENT_RECORDED', 'PAYMENT_REFUNDED', 'PAYMENT_STARTED', 'REFUND_COMPLETED', 'REFUND_FAILED', 'REFUND_REQUESTED', 'REFUND_RETRIED', 'REORDER_POINT_CHANGED', 'STOCK_ADJUSTED', 'STOCK_RECEIVED', 'STOCK_TRANSFERRED'])), name='audit_action_check'), models.CheckConstraint(condition=models.Q(('entity_type__in', ['ORDER', 'PAYMENT', 'REFUND', 'STOCK_ITEM'])), name='audit_entity_type_check')],
            },
        ),
    ]
