# Generated by Django 5.2.17 on 2026-10-04 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'suppliers_supplier',
                'ordering': ('legal_name',),
                'indexes': [models.Index(fields=['organization', 'is_active'], name='suppliers_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'tax_id'), name='suppliers_supplier_org_tax_id_uniq'), models.CheckConstraint(condition=models.Q(('tax_id__regex', '^[0-9A-Z]{12}[0-9]{2}$')), name='suppliers_supplier_tax_id_format_check')],
            },
        ),
    ]
