# Generated by Django 5.2.17 on 2026-10-06 15:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events_outbox',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['occurred_at'], name='events_outbox_pending_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=200)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.outboxevent')),
            ],
            options={
                'db_table': 'events_processed',
                'constraints': [models.UniqueConstraint(fields=('event', 'handler'), name='events_processed_uniq')],
            },
        ),
    ]
