# Generated by Django 5.2.17 on 2026-10-05 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=60)),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20)),
                ('response_status', models.PositiveSmallIntegerField(null=True)),
                ('response_body', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idempotency_record',
                'indexes': [models.Index(fields=['expires_at'], name='idempotency_expires_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'operation', 'key'), name='idempotency_record_user_op_key_uniq')],
            },
        ),
    ]
