# Generated by Django 5.2.17 on 2026-10-07 14:42

import apps.shipping.domain.status
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('order_reference', models.CharField(max_length=30)),
                ('carrier', models.CharField(max_length=60)),
                ('tracking_code', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED')], max_length=12)),
                ('shipped_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_source', models.CharField(blank=True, choices=[('PROVIDER', 'PROVIDER'), ('MANUAL', 'MANUAL')], max_length=10)),
                ('delivery_note', models.CharField(blank=True, max_length=200)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipping_shipment',
                'ordering': ('-shipped_at',),
                'indexes': [models.Index(condition=models.Q(('status', apps.shipping.domain.status.ShipmentStatus['IN_TRANSIT'])), fields=['next_check_at'], name='shipping_in_transit_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_id',), name='shipping_one_shipment_per_order_uniq'), models.UniqueConstraint(fields=('carrier', 'tracking_code'), name='shipping_tracking_code_uniq'), models.CheckConstraint(condition=models.Q(('status__in', ['DELIVERED', 'IN_TRANSIT'])), name='shipping_status_check'), models.CheckConstraint(condition=models.Q(models.Q(('delivered_at__isnull', False), ('delivery_source__in', ['MANUAL', 'PROVIDER']), ('status', apps.shipping.domain.status.ShipmentStatus['DELIVERED'])), models.Q(('delivered_at__isnull', True), ('delivery_source', ''), ('status', apps.shipping.domain.status.ShipmentStatus['IN_TRANSIT'])), _connector='OR'), name='shipping_delivery_consistency_check')],
            },
        ),
    ]
