# Generated by Django 5.2.17 on 2026-10-05 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'customers_segment',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.customersegment')),
            ],
            options={
                'db_table': 'customers_customer',
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('is_billing', models.BooleanField(default=False)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'customers_address',
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_billing', True)), fields=('customer',), name='customers_address_one_billing_uniq'), models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('customer',), name='customers_address_one_default_shipping_uniq'), models.CheckConstraint(condition=models.Q(('postal_code__regex', '^[0-9]{8}$')), name='customers_address_postal_code_format_check'), models.CheckConstraint(condition=models.Q(('state__in', ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'])), name='customers_address_state_check')],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'customers_contact',
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer',), name='customers_contact_one_primary_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('phone', ''), _negated=True), _connector='OR'), name='customers_contact_channel_required_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='customersegment',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='customers_segment_org_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customersegment',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9_-]{2,30}$')), name='customers_segment_code_format_check'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'is_active'], name='customers_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'tax_id'), name='customers_customer_org_tax_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('tax_id__regex', '^[0-9A-Z]{12}[0-9]{2}$')), name='customers_customer_tax_id_format_check'),
        ),
    ]
