# Generated by Django 5.2.17 on 2026-10-06 15:03

import apps.payments.domain.status
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('order_reference', models.CharField(max_length=30)),
                ('method', models.CharField(choices=[('CARD', 'CARD'), ('MANUAL', 'MANUAL')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('FAILED', 'FAILED'), ('REFUNDED', 'REFUNDED')], max_length=10)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('decline_reason', models.CharField(blank=True, max_length=100)),
                ('manual_reference', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_refund',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='payments_order_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('status', apps.payments.domain.status.PaymentStatus['PENDING'])), fields=['next_attempt_at'], name='payments_pending_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', apps.payments.domain.status.PaymentStatus['APPROVED'])), fields=('order_id',), name='payments_one_approved_per_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', apps.payments.domain.status.PaymentStatus['PENDING'])), fields=('order_id',), name='payments_one_pending_per_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_amount_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['APPROVED', 'DECLINED', 'FAILED', 'PENDING', 'REFUNDED'])), name='payments_status_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['CARD', 'MANUAL'])), name='payments_method_check'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', apps.payments.domain.status.PaymentMethod['MANUAL']), _negated=True), models.Q(('manual_reference', ''), _negated=True), _connector='OR'), name='payments_manual_reference_check'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [apps.payments.domain.status.RefundStatus['PENDING'], apps.payments.domain.status.RefundStatus['SUCCEEDED']])), fields=('payment',), name='payments_one_active_refund_uniq'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_refund_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['FAILED', 'PENDING', 'SUCCEEDED'])), name='payments_refund_status_check'),
        ),
    ]
