# Generated by Django 5.2.17 on 2026-10-07 16:30

import apps.payments.domain.status
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # Índice em tabela com volume: CONCURRENTLY não bloqueia escritas durante o deploy (exige
    # migration fora de transação).
    atomic = False

    dependencies = [
        ('identity', '0002_organizations_teams_and_email_login'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='payment',
            index=models.Index(condition=models.Q(('status__in', [apps.payments.domain.status.PaymentStatus['APPROVED'], apps.payments.domain.status.PaymentStatus['REFUNDED']])), fields=['organization', 'completed_at'], name='payments_org_revenue_idx'),
        ),
        AddIndexConcurrently(
            model_name='refund',
            index=models.Index(condition=models.Q(('status', apps.payments.domain.status.RefundStatus['SUCCEEDED'])), fields=['organization', 'completed_at'], name='payments_org_refunded_idx'),
        ),
    ]
