# Generated by Django 5.2.17 on 2026-10-04 12:50

import apps.identity.domain.permissions
import apps.identity.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_organization',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',)},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.identity.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('SALES', 'SALES'), ('WAREHOUSE', 'WAREHOUSE'), ('FINANCE', 'FINANCE'), ('VIEWER', 'VIEWER')], default=apps.identity.domain.permissions.Role['VIEWER'], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='identity.organization'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'db_table': 'identity_team',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='identity.team'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='identity_user_org_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False), ('is_superuser', True), _connector='OR'), name='identity_user_org_required_check'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='identity_user_email_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('name'), name='identity_team_org_name_uniq'),
        ),
    ]
